title       = "usgs"
baseURL     = "https://usgs-cli.tamnd.com/"
description = "A command line for usgs."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/usgs-cli"
